site_name: Jetpack Compose Journey
site_description: 'Conteúdo sobre Jetpack Compose voltado para iniciantes'
site_author: 'Jesus Ericks'
site_url: 'https://github.com/jsericksk/Jetpack-Compose-Journey'
edit_uri: 'tree/main/docs/'

## Local dev
dev_addr: 127.0.0.1:3333

theme:
  name: material
  language: pt-BR
  font:
    code: Jetbrains Mono
  palette:
    # Light mode
    - scheme: default
      primary: black
      accent: red
      toggle:
        icon: material/weather-night
        name: Mudar para tema light

    # Dark mode
    - scheme: slate
      primary: green
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Mudar para tema light

# Navigation
nav:
  - 'Introdução': index.md
  - 'Conhecimentos básicos iniciais': basic.md
  - 'Layouts':
    - 'Column': layouts/column.md
    - 'Row': layouts/row.md
    - 'Box': layouts/box.md
    - 'ConstraintLayout': layouts/constraintlayout.md
  - 'Previews: Visualize seus layouts': previews.md
  - 'Theme: Modificando o tema do app': theme.md
  - 'Componentes importantes':
    - 'Text': components/text.md
    - 'TextField': components/textfield.md
    - 'Button': components/button.md
    - 'Image': components/image.md
    - 'Card': components/card.md
    - 'Switch': components/switch.md
    - 'Checkbox': components/checkbox.md
    - 'Slider': components/slider.md
    - 'Scaffold': components/scaffold.md
    - 'Navigation Drawer': components/navigationdrawer.md
    - 'Outros componentes': components/others.md
  - 'Modifier: Um modificador onipresente': modifiers.md
  - 'Estado no Compose': state.md
  - 'Listas': lists.md
  - 'Side Effects':
    - 'LaunchedEffect': side-effects/launchedeffect.md
    - 'rememberCoroutineScope': side-effects/remembercoroutinescope.md
    - 'rememberUpdatedState': side-effects/rememberupdatedstate.md
    - 'DisposableEffect': side-effects/disposableeffect.md

markdown_extensions:
  - pymdownx.tasklist
  - pymdownx.emoji
  - pymdownx.betterem

  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

  - pymdownx.highlight
  - pymdownx.inlinehilite
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - admonition
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - git-revision-date-localized:
      type: date
      locale: pt