site_name: Jetpack Compose Journey
site_description: 'Conteúdo sobre Jetpack Compose voltado para iniciantes'
site_author: 'Jesus Ericks'
site_url: 'https://github.com/jsericksk/Jetpack-Compose-Journey'
edit_uri: 'tree/main/docs/'

## Local dev
dev_addr: 127.0.0.1:3333

theme:
  name: material
  language: pt-BR
  font:
    code: Jetbrains Mono
  palette:
    # Light mode
    - scheme: default
      primary: black
      accent: red
      toggle:
        icon: material/weather-night
        name: Mudar para tema light

    # Dark mode
    - scheme: slate
      primary: green
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Mudar para tema light

# Navigation
nav:
  - 'Introdução': index.md
  - 'Conhecimentos básicos iniciais': basic.md
  - 'Layouts':
    - 'Column': layouts/column.md
    - 'Row': layouts/row.md
    - 'Box': layouts/box.md
    - 'ConstraintLayout': layouts/constraintlayout.md
  - 'Previews: Visualize seus layouts': previews.md
  - 'Componentes 01: Text, TextField, Button, Image...':
    - 'Text': components-1/text.md
    - 'TextField': components-1/textfield.md
    - 'Button': components-1/button.md
    - 'Image': components-1/image.md
    - 'Card': components-1/card.md
    - 'Switch': components-1/switch.md

markdown_extensions:
  - pymdownx.tasklist
  - pymdownx.emoji
  - pymdownx.betterem

  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

  - pymdownx.highlight
  - pymdownx.inlinehilite
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - admonition
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - git-revision-date-localized:
      type: date
      locale: pt